### ISSUE TITLE
Portal create to much particles

### ISSUE THREAD

**Issue by FurrO2** [Jarada/WuufusWaygates#16]
Hello, i have this weird bug and i don't know how to fix it :
the bug is, there is too much particles on the 3x3 portal ( near 2800 ) compare to the 2x3 ( 230 particles ~)
![image](https://github.com/Jarada/WuufusWaygates/assets/133584837/123f09b6-4ae8-4984-8208-455a64e6318c)
![image](https://github.com/Jarada/WuufusWaygates/assets/133584837/7100b01d-f203-49d8-84bc-8eaa529f8be6)

I'm using paper on 1.20.1, and the latest version of this plugins ( 1.4.1 ).

**Comment by FurrO2** [comment]
![image](https://github.com/Jarada/WuufusWaygates/assets/133584837/7158b4f8-2f71-4cc5-b327-e6f1c287a3a0)
![image](https://github.com/Jarada/WuufusWaygates/assets/133584837/01dd498c-87b0-4ff7-887f-b8b6e1bd33ea)
![2023-11-17_18 20 42](https://github.com/Jarada/WuufusWaygates/assets/133584837/069158ef-3030-4002-9989-70d7d23def62)

**Comment by Jarada** [comment]
Hi there, thank you for this bug report.

Can you answer a few questions?

1. Does this issue exist on all 3x3 gates?
2. Does this issue persist even on server restarts?
3. What is the config setting `WG_GATE_EFFECT_PARTICLES`?

Thanks!

**Comment by FurrO2** [comment]
1 : After some tests, it appears that this bug can also manifest on other shape of portals.

2: Yes, even after deleting the configuration file.

3:
```
  MAX_AREA: 200
  MENU_SIZE: compact
  WG_NAME_MAX_LENGTH: 18
  WG_DESC_MAX_LENGTH: 100
  WG_NETWORK_NAME_MAX_LENGTH: 18
  WG_CONTROLLER_DISTANCE: 50
  WG_GATE_ACTIVATION_TIME: 20
  WG_GATE_EFFECT_PARTICLES: normal
  WG_GATE_MINIMAL_DISTANCE: 1
  WG_GATE_ICON_CHANGE_CONSUMES: false
  WG_CONTROL_CREATOR_CONSUMES: true
  WG_CONSTRUCTOR_CONSUMES: true
  WG_KEY_CONSUMES: false
  WG_KEY_PERMANENT: false
  WG_ZOMBIE_PIGMAN_ALLOWED: false
  WG_PRIVATE_GATES_ALLOW_TRAVEL: false
  BLOCKS_REQUIRED:
    '1':
      EMERALD_BLOCK: 2
```
